# Generated by Django 3.2.12 on 2022-02-27 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Author name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Author name')),
                ('name_ne', models.CharField(max_length=255, null=True, verbose_name='Author name')),
                ('about_author', models.TextField(blank=True, null=True, verbose_name='About author')),
                ('about_author_en', models.TextField(blank=True, null=True, verbose_name='About author')),
                ('about_author_ne', models.TextField(blank=True, null=True, verbose_name='About author')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_ne', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('image', models.FileField(blank=True, default=None, max_length=255, null=True, upload_to='books/images/')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ne', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('isbn', models.CharField(blank=True, max_length=13, verbose_name='ISBN')),
                ('number_of_pages', models.IntegerField(verbose_name='Number of pages')),
                ('language', models.CharField(choices=[('english', 'English'), ('nepali', 'Nepali'), ('Maithali', 'Maithali'), ('Tharu', 'Tharu')], max_length=40, verbose_name='Language')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Weight in grams')),
                ('published_date', models.DateField(verbose_name='Published Date')),
                ('edition', models.CharField(blank=True, max_length=255, null=True, verbose_name='Edition')),
                ('grade', models.CharField(blank=True, choices=[('grade_one', 'Grade 1'), ('grade_two', 'Grade 2'), ('grade_three', 'Grade 3')], max_length=40, null=True, verbose_name='Grade')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is published')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title')),
                ('meta_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title')),
                ('meta_title_ne', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords')),
                ('meta_keywords_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords')),
                ('meta_keywords_ne', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords')),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description')),
                ('meta_description_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description')),
                ('meta_description_ne', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description')),
                ('og_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph title')),
                ('og_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph title')),
                ('og_title_ne', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph title')),
                ('og_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph description')),
                ('og_description_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph description')),
                ('og_description_ne', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph description')),
                ('og_image', models.FileField(blank=True, default=None, max_length=255, null=True, upload_to='books/og_image/')),
                ('og_locale', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph locale')),
                ('og_locale_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph locale')),
                ('og_locale_ne', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph locale')),
                ('og_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph type')),
                ('og_type_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph type')),
                ('og_type_ne', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph type')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Category name')),
                ('name_ne', models.CharField(max_length=255, null=True, verbose_name='Category name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=256, null=True, unique=True, verbose_name='Name')),
                ('name_ne', models.CharField(max_length=256, null=True, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_wish_list', to='book.book', verbose_name='Book')),
            ],
            options={
                'verbose_name': 'Wish list',
                'verbose_name_plural': 'Wish lists',
            },
        ),
    ]
