# Generated by Django 3.2.11 on 2022-01-10 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publisher', '0003_auto_20220110_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Author name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Author name')),
                ('name_ne', models.CharField(max_length=255, null=True, verbose_name='Author name')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=256, null=True, unique=True, verbose_name='Name')),
                ('name_ne', models.CharField(max_length=256, null=True, unique=True, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Category name')),
                ('name_ne', models.CharField(max_length=255, null=True, verbose_name='Category name')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='book_category_category', to='book.category', verbose_name='Parent category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_ne', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ne', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('isbn', models.CharField(max_length=255, verbose_name='ISBN')),
                ('number_of_pages', models.IntegerField(verbose_name='Number of pages')),
                ('language', models.CharField(choices=[('nepali', 'Nepali'), ('english', 'English')], max_length=40, verbose_name='Language')),
                ('weight', models.IntegerField(verbose_name='Weight in grams')),
                ('published_date', models.DateTimeField(verbose_name='Published Date')),
                ('edition', models.CharField(max_length=255, verbose_name='Edition')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title')),
                ('meta_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title')),
                ('meta_title_ne', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords')),
                ('meta_keywords_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords')),
                ('meta_keywords_ne', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords')),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description')),
                ('meta_description_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description')),
                ('meta_description_ne', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description')),
                ('og_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph title')),
                ('og_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph title')),
                ('og_title_ne', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph title')),
                ('og_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph description')),
                ('og_description_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph description')),
                ('og_description_ne', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph description')),
                ('og_image', models.FileField(blank=True, default=None, max_length=255, null=True, upload_to='books/')),
                ('og_locale', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph locale')),
                ('og_locale_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph locale')),
                ('og_locale_ne', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph locale')),
                ('og_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph type')),
                ('og_type_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph type')),
                ('og_type_ne', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph type')),
                ('authors', models.ManyToManyField(related_name='book_book_authors', to='book.Author', verbose_name='Author')),
                ('categories', models.ManyToManyField(related_name='book_book_categories', to='book.Category', verbose_name='Category')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_book_publisher', to='publisher.publisher', verbose_name='Publisher')),
                ('tags', models.ManyToManyField(related_name='book_book_tags', to='book.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
