# Generated by Django 3.2.11 on 2022-01-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.FileField(blank=True, default=None, max_length=255, null=True, upload_to='books/'),
        ),
    ]
