# Generated by Django 3.2.12 on 2022-03-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, default=None, max_length=255, null=True, upload_to='books/category/images/'),
        ),
    ]
