# Generated by Django 3.2.12 on 2022-03-10 05:08

from django.db import migrations
from apps.book.models import Category

class Migration(migrations.Migration):

    def fix_book_categories(apps, schema_editor):
        Category = apps.get_model("book", "Category")
        Book = apps.get_model("book", "Book")
        try:
            category_to_keep = Category.objects.get(name='Pictorial Story')
            categories_to_remove_ids = Category.objects.filter(
                name__in=['Picture', 'Picture Story']
            ).values_list('id', flat=True)
            books = Book.objects.filter(
                categories__in=categories_to_remove_ids
            )
            for book in books:
                book.categories.set([category_to_keep.id])
            Category.objects.filter(id__in=categories_to_remove_ids).delete()

        except Category.DoesNotExist:
            pass

    dependencies = [
        ('book', '0003_category_image'),
    ]

    operations = [migrations.RunPython(fix_book_categories)]
