# Generated by Django 3.2.11 on 2022-01-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20220113_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='created_by',
        ),
    ]
