# Generated by Django 3.2.12 on 2022-07-18 08:20

from django.db import migrations, models

def migrate_book_grade_enums(apps, schema_editor):
    Book = apps.get_model('book', 'Book')
    for old_grade, new_grade in [
            ('grade_one', 'grade_1'),
            ('grade_two', 'grade_2'),
            ('grade_three', 'grade_3'),
    ]:
        Book.objects.filter(grade=old_grade).update(grade=new_grade)


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_fix_book_categories'),
    ]

    operations = [
        migrations.RunPython(migrate_book_grade_enums),
        migrations.AlterField(
            model_name='book',
            name='grade',
            field=models.CharField(blank=True, choices=[('grade_1', 'Grade 1'), ('grade_2', 'Grade 2'), ('grade_3', 'Grade 3')], max_length=40, null=True, verbose_name='Grade'),
        ),
    ]
