# Generated by Django 3.2.11 on 2022-01-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20220114_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(verbose_name='Published Date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Weight in grams'),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='book_book_tags', to='book.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title_ne',
            field=models.CharField(max_length=255, null=True, blank=True, verbose_name='Title'),
        ),
    ]
