# Generated by Django 3.2.16 on 2023-12-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20230119_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('nepali', 'Nepali'), ('Maithali', 'Maithali'), ('Tharu', 'Tharu'), ('bilingual', 'Bilingual')], max_length=40, verbose_name='Language'),
        ),
    ]
