# Generated by Django 3.2.11 on 2022-01-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20220117_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about_author',
            field=models.TextField(blank=True, null=True, verbose_name='About author'),
        ),
        migrations.AddField(
            model_name='author',
            name='about_author_en',
            field=models.TextField(blank=True, null=True, verbose_name='About author'),
        ),
        migrations.AddField(
            model_name='author',
            name='about_author_ne',
            field=models.TextField(blank=True, null=True, verbose_name='About author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Edition'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title_ne',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
