# Generated by Django 3.2.11 on 2022-01-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20220118_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=10, verbose_name='ISBN'),
        ),
    ]
