# Generated by Django 3.2.11 on 2022-02-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20220128_1303'),
        ('book', '0010_alter_book_isbn'),
    ]

    operations = [
    ]
