# Generated by Django 3.2.11 on 2022-02-04 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_merge_0009_auto_20220128_1303_0010_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_wish_list', to='book.book', verbose_name='Book'),
        ),
    ]
