# Generated by Django 3.2.12 on 2022-02-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_wishlist_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='grade',
            field=models.CharField(blank=True, choices=[('grade_one', 'Grade 1'), ('grade_two', 'Grade 2'), ('grade_three', 'Grade 3'), ('grade_four', 'Grade 4'), ('grade_five', 'Grade 5'), ('grade_six', 'Grade 6'), ('grade_seven', 'Grade 7'), ('grade_eight', 'Grade 8'), ('grade_nine', 'Grade 9'), ('grade_ten', 'Grade 10'), ('grade_eleven', 'Grade 11'), ('grade_twelve', 'Grade 12')], max_length=40, null=True, verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is published'),
        ),
    ]
