# Generated by Django 3.2.12 on 2022-02-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_auto_20220209_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='grade',
            field=models.CharField(blank=True, choices=[('grade_one', 'Grade 1'), ('grade_two', 'Grade 2'), ('grade_three', 'Grade 3')], max_length=40, null=True, verbose_name='Grade'),
        ),
    ]
