# Generated by Django 3.2.12 on 2022-02-10 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_book_created_by'),
        ('book', '0014_alter_book_grade'),
    ]

    operations = [
    ]
