# Generated by Django 3.2.12 on 2022-02-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_merge_0013_book_created_by_0014_alter_book_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('nepali', 'Nepali'), ('Maithali', 'Maithali'), ('Tharu', 'Tharu')], max_length=40, verbose_name='Language'),
        ),
    ]
