# Generated by Django 3.2.10 on 2022-01-06 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_number', models.IntegerField(verbose_name='Ward Number')),
                ('local_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local address')),
                ('pan_number', models.CharField(max_length=255, unique=True, verbose_name='Pan number')),
                ('vat_number', models.CharField(max_length=255, unique=True, verbose_name='Vat number')),
                ('publisher_name', models.CharField(max_length=255, verbose_name='Publisher name')),
                ('publisher_email', models.EmailField(max_length=255, verbose_name='Publisher email')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publisher_publisher_district', to='common.district', verbose_name='District')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publisher_publisher_municipality', to='common.municipality', verbose_name='Municipality')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publisher_publisher_province', to='common.province', verbose_name='Province')),
            ],
            options={
                'verbose_name': 'Publisher',
                'verbose_name_plural': 'Publishers',
            },
        ),
    ]
