# Generated by Django 3.2.12 on 2022-04-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='internal_code',
            field=models.CharField(choices=[('parichaya', 'Parichaya'), ('bhundipuran', 'Bhundipuran'), ('kathalaya', 'Kathalaya'), ('ekata', 'Ekata')], default=None, max_length=40, null=True, verbose_name='Internal code'),
        ),
    ]
