# Generated by Django 3.2.11 on 2022-01-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0004_alter_publisher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='pan_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Pan number'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='vat_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Vat number'),
        ),
    ]
