# Generated by Django 3.2.11 on 2022-01-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=520, null=True, verbose_name='Full Name'),
        ),
    ]
