# Generated by Django 3.2.11 on 2022-01-12 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0003_auto_20220110_1107'),
        ('institution', '0003_auto_20220110_1445'),
        ('school', '0003_auto_20220110_1107'),
        ('user', '0005_merge_20220112_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_user_institution', to='institution.institution', verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='user',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_user_publisher', to='publisher.publisher', verbose_name='Publisher'),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_user_school', to='school.school', verbose_name='School'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
