# Generated by Django 3.2.11 on 2022-01-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20220112_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, max_length=255, upload_to='user/images/'),
        ),
    ]
