# Generated by Django 3.2.11 on 2022-02-02 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_school_email'),
        ('institution', '0006_remove_institution_email'),
        ('publisher', '0006_remove_publisher_email'),
        ('user', '0008_merge_0007_auto_20220126_1930_0007_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution_user', to='institution.institution', verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='user',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher_user', to='publisher.publisher', verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_user', to='school.school', verbose_name='School'),
        ),
    ]
