# Generated by Django 3.2.12 on 2022-02-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20220202_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('moderator', 'Moderator'), ('publisher', 'Publisher'), ('institutional_user', 'Institutional User'), ('school_admin', 'School Admin'), ('individual_user', 'Individual User')], default='individual_user', max_length=40, verbose_name='User Type'),
        ),
    ]
