# Generated by Django 3.2.12 on 2022-02-27 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('ward_number', models.IntegerField(verbose_name='Ward Number')),
                ('local_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local address')),
                ('pan_number', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Pan number')),
                ('vat_number', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Vat number')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institution_institution_district', to='common.district', verbose_name='District')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institution_institution_municipality', to='common.municipality', verbose_name='Municipality')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institution_institution_province', to='common.province', verbose_name='Province')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
            },
        ),
    ]
