# Generated by Django 3.2.12 on 2022-03-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='library_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
