# Generated by Django 3.2.11 on 2022-01-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_auto_20220106_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='local_address_en',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='local_address_ne',
        ),
    ]
