# Generated by Django 3.2.11 on 2022-01-13 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_auto_20220113_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='email',
        ),
    ]
