# Generated by Django 3.2.12 on 2022-02-27 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=256, null=True, unique=True, verbose_name='Name')),
                ('name_ne', models.CharField(max_length=256, null=True, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Category name')),
                ('name_ne', models.CharField(max_length=255, null=True, verbose_name='Category name')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blog_category', to='blog.category', verbose_name='Parent category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, verbose_name='Blog title')),
                ('title_en', models.TextField(blank=True, null=True, verbose_name='Blog title')),
                ('title_ne', models.TextField(blank=True, null=True, verbose_name='Blog title')),
                ('description', models.TextField(blank=True, verbose_name='Blog Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Blog Description')),
                ('description_ne', models.TextField(blank=True, null=True, verbose_name='Blog Description')),
                ('image', models.FileField(blank=True, default=None, max_length=255, null=True, upload_to='blog/images/', verbose_name='Blog image')),
                ('published_date', models.DateField(verbose_name='Published Date')),
                ('blog_publish_type', models.CharField(choices=[('publish', 'Publish'), ('draft', 'Draft')], default='draft', max_length=40, verbose_name='Publish Type')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title')),
                ('meta_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title')),
                ('meta_title_ne', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords')),
                ('meta_keywords_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords')),
                ('meta_keywords_ne', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords')),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description')),
                ('meta_description_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description')),
                ('meta_description_ne', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description')),
                ('og_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph title')),
                ('og_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph title')),
                ('og_title_ne', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph title')),
                ('og_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph description')),
                ('og_description_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph description')),
                ('og_description_ne', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph description')),
                ('og_image', models.FileField(blank=True, default=None, max_length=255, null=True, upload_to='blog/og_image/')),
                ('og_locale', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph locale')),
                ('og_locale_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph locale')),
                ('og_locale_ne', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph locale')),
                ('og_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph type')),
                ('og_type_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph type')),
                ('og_type_ne', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open graph type')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_categories', to='blog.category', verbose_name='Blog category')),
                ('tags', models.ManyToManyField(blank=True, related_name='blog_tags', to='blog.Tag', verbose_name='Blog Tags')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
