# Generated by Django 3.2.12 on 2022-02-27 09:33

import apps.common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('payment', 'Payment'), ('order', 'Order'), ('package', 'Package')], max_length=30, verbose_name='Type')),
                ('image', models.FileField(upload_to=apps.common.models.activity_file_path, verbose_name='Activity log image')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=256, null=True, unique=True, verbose_name='Name')),
                ('name_ne', models.CharField(max_length=256, null=True, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=256, null=True, unique=True, verbose_name='Name')),
                ('name_ne', models.CharField(max_length=256, null=True, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Province',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('name_en', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('name_ne', models.CharField(max_length=256, null=True, verbose_name='Name')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_municipality_district', to='common.district', verbose_name='District')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_municipality_province', to='common.province', verbose_name='Province')),
            ],
            options={
                'verbose_name': 'Municipality',
                'verbose_name_plural': 'Municipalities',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_district_province', to='common.province', verbose_name='Province'),
        ),
    ]
