# Generated by Django 3.2.10 on 2022-01-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='name_en',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_ne',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='name_en',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='name_ne',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='province',
            name='name_en',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='province',
            name='name_ne',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='Name'),
        ),
    ]
