# Generated by Django 3.2.10 on 2022-01-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20220106_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='name_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='name_ne',
            field=models.CharField(max_length=256, null=True, verbose_name='Name'),
        ),
    ]
