# Generated by Django 3.2.12 on 2022-02-21 20:01

import apps.common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0003_auto_20220110_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('payment', 'Payment'), ('order', 'Order'), ('package', 'Package')], max_length=30, verbose_name='Type')),
                ('image', models.FileField(upload_to=apps.common.models.activity_image_path, verbose_name='Activity log image')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
        ),
    ]
