# Generated by Django 3.2.12 on 2022-03-02 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20220302_1008'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0003_auto_20220302_1008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLogImage',
        ),
        migrations.AddField(
            model_name='activitylogfile',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
    ]
