# Generated by Django 3.2.12 on 2022-02-25 04:14

import apps.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_activitylogimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('payment', 'Payment'), ('order', 'Order'), ('package', 'Package')], max_length=30, verbose_name='Type')),
                ('file', models.FileField(upload_to=apps.common.models.activity_file_path, verbose_name='Activity log file')),
            ],
        ),
        migrations.RemoveField(
            model_name='activitylogimage',
            name='created_by',
        ),
    ]
