# Generated by Django 3.2.12 on 2022-06-27 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20220302_1008'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='common.district', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='school',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='common.municipality', verbose_name='Municipality'),
        ),
        migrations.AlterField(
            model_name='school',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='common.province', verbose_name='Province'),
        ),
    ]
