# Generated by Django 3.2.12 on 2022-02-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_school_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='School id'),
        ),
    ]
