# Generated by Django 3.2.11 on 2022-01-27 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_received', 'Order received'), ('order_packed', 'Order packed'), ('order_completed', 'Order completed'), ('order_cancelled', 'Order cancelled'), ('general', 'General')], default='general', max_length=40, verbose_name='Notification Type')),
                ('title', models.TextField(verbose_name='Title')),
                ('read', models.BooleanField(default=False, help_text='Whether notification has been marked as read', verbose_name='Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When notification was created', verbose_name='Created at')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='For user')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
