# Generated by Django 3.2.12 on 2022-02-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title_en',
            field=models.TextField(null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_ne',
            field=models.TextField(null=True, verbose_name='Title'),
        ),
    ]
