# Generated by Django 3.2.12 on 2022-02-17 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20220210_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title_ne',
        ),
    ]
