# Generated by Django 3.2.11 on 2022-01-19 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0008_auto_20220118_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.BigIntegerField(verbose_name='Total Price')),
                ('order_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('received', 'Received'), ('packed', 'Packed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='received', max_length=40, verbose_name='Order status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_cart_item', to='book.book', verbose_name='Book')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
            },
        ),
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('price', models.BigIntegerField(verbose_name='Price')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('isbn', models.CharField(max_length=255, verbose_name='ISBN')),
                ('edition', models.CharField(max_length=255, verbose_name='Edition')),
                ('total_price', models.BigIntegerField(verbose_name='Total Price')),
                ('image', models.FileField(blank=True, default=None, max_length=255, null=True, upload_to='orders/books/images/')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_order_cart_item', to='book.book', verbose_name='Book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_order', to='order.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Book Order',
                'verbose_name_plural': 'Book Orders',
            },
        ),
    ]
