# Generated by Django 3.2.11 on 2022-01-18 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0008_alter_book_title_ne'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('isbn', models.CharField(max_length=255, verbose_name='ISBN')),
                ('edition', models.CharField(max_length=255, verbose_name='Edition')),
                ('price', models.BigIntegerField(verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Book Order',
                'verbose_name_plural': 'Book Orders',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.BigIntegerField(verbose_name='Total Price')),
                ('order_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('book_orders', models.ManyToManyField(blank=True, related_name='book_orders', to='order.BookOrder', verbose_name='Book orders')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_cart_item', to='book.book', verbose_name='Book')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
            },
        ),
    ]
