# Generated by Django 3.2.11 on 2022-01-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorder',
            name='isbn',
            field=models.CharField(max_length=10, verbose_name='ISBN'),
        ),
    ]
