# Generated by Django 3.2.12 on 2022-04-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderwindow',
            name='type',
            field=models.CharField(blank=True, choices=[('school', 'School'), ('institution', 'Institution')], max_length=40, verbose_name='Order window type'),
        ),
    ]
