# Generated by Django 3.2.11 on 2022-01-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_bookorder_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorder',
            name='isbn',
            field=models.CharField(max_length=13, verbose_name='ISBN'),
        ),
    ]
