# Generated by Django 3.2.11 on 2022-02-06 04:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_bookorder_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_placed_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Order placed at'),
            preserve_default=False,
        ),
    ]
