# Generated by Django 3.2.12 on 2022-04-04 05:39

from django.db import migrations


def migrate_existing_order_windows(apps, schema_editor):
    from apps.order.models import OrderWindow
    OrderWindow.objects.all().update(type=OrderWindow.OrderWindowType.SCHOOL)


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderwindow_type'),
    ]

    operations = [migrations.RunPython(migrate_existing_order_windows)]
