# Generated by Django 3.2.12 on 2022-04-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_migrate_existing_order_windows'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookorder',
            name='grade',
            field=models.CharField(blank=True, choices=[('grade_one', 'Grade 1'), ('grade_two', 'Grade 2'), ('grade_three', 'Grade 3')], max_length=40, null=True, verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='language',
            field=models.CharField(blank=True, choices=[('english', 'English'), ('nepali', 'Nepali'), ('Maithali', 'Maithali'), ('Tharu', 'Tharu')], max_length=40, null=True, verbose_name='Language'),
        ),
    ]
