# Generated by Django 3.2.12 on 2022-02-10 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20220208_1042'),
        ('order', '0004_order_order_placed_at'),
    ]

    operations = [
    ]
