# Generated by Django 3.2.12 on 2022-02-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_merge_20220210_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_placed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Order placed at'),
        ),
    ]
