# Generated by Django 3.2.12 on 2022-06-27 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_migrate_grade_and_language_in_book_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='assigned_order_window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order.orderwindow'),
        ),
    ]
