# Generated by Django 3.2.12 on 2022-07-13 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_fix_book_categories'),
        ('order', '0007_alter_order_assigned_order_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorder',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_book', to='book.book', verbose_name='Book'),
        ),
    ]
