# Generated by Django 3.2.12 on 2022-07-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_bookorder_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorder',
            name='grade',
            field=models.CharField(blank=True, choices=[('grade_1', 'Grade 1'), ('grade_2', 'Grade 2'), ('grade_3', 'Grade 3')], max_length=40, null=True, verbose_name='Grade'),
        ),
    ]
