# Generated by Django 3.2.16 on 2023-01-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_bookorder_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorder',
            name='grade',
            field=models.CharField(blank=True, choices=[('ecd', 'ECD'), ('grade_1', 'Grade 1'), ('grade_2', 'Grade 2'), ('grade_3', 'Grade 3'), ('grade_4', 'Grade 4'), ('grade_5', 'Grade 5')], max_length=40, null=True, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='language',
            field=models.CharField(blank=True, choices=[('english', 'English'), ('nepali', 'Nepali'), ('Maithali', 'Maithali'), ('Tharu', 'Tharu'), ('bilingual', 'BILINGUAL')], max_length=40, null=True, verbose_name='Language'),
        ),
    ]
