# Generated by Django 3.2.16 on 2023-12-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20230119_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderwindow',
            name='enable_incentive',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderwindow',
            name='incentive_max',
            field=models.PositiveSmallIntegerField(default=120, help_text='Max incentive count value. eg: 120'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderwindow',
            name='incentive_multiplier',
            field=models.PositiveSmallIntegerField(default=4, help_text='Generate incentive count by multiplying with. eg: 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderwindow',
            name='incentive_quantity_threshold',
            field=models.PositiveSmallIntegerField(default=10, help_text='Least quantity count required for incentive. eg: 10'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='edition',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Edition'),
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='language',
            field=models.CharField(blank=True, choices=[('english', 'English'), ('nepali', 'Nepali'), ('Maithali', 'Maithali'), ('Tharu', 'Tharu'), ('bilingual', 'Bilingual')], max_length=40, null=True, verbose_name='Language'),
        ),
    ]
