# Generated by Django 3.2.16 on 2023-02-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20230119_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorder',
            name='grade',
            field=models.CharField(blank=True, choices=[('ecd', 'ECD'), ('grade_1', 'Grade 1'), ('grade_2', 'Grade 2'), ('grade_3', 'Grade 3')], max_length=40, null=True, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='language',
            field=models.CharField(blank=True, choices=[('english', 'English'), ('nepali', 'Nepali'), ('Maithali', 'Maithali'), ('Tharu', 'Tharu'), ('bilingual', 'Bilingual')], max_length=40, null=True, verbose_name='Language'),
        ),
    ]
