# Generated by Django 3.2.11 on 2022-02-04 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='publish_type',
            new_name='faq_publish_type',
        ),
    ]
