# Generated by Django 3.2.12 on 2022-03-11 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0002_initial'),
        ('order', '0002_initial'),
        ('common', '0004_auto_20220302_1008'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In transit'), ('issue', 'Issue'), ('delivered', 'Delivered')], default='pending', max_length=40, verbose_name='Courier package status')),
                ('total_price', models.IntegerField(default=0, verbose_name='Total price')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='Total quantity')),
                ('order_window', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='order.orderwindow', verbose_name='Order window')),
                ('related_orders', models.ManyToManyField(related_name='courier_related_orders', to='order.Order', verbose_name='School related order')),
            ],
            options={
                'verbose_name': 'Courier Package',
                'verbose_name_plural': 'Courier Packages',
            },
        ),
        migrations.CreateModel(
            name='PublisherPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issue', 'Issue'), ('delivered', 'Delivered')], default='pending', max_length=40, verbose_name='Publisher package status')),
                ('total_price', models.IntegerField(default=0, verbose_name='Total price')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='Total quantity')),
                ('order_window', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='order.orderwindow', verbose_name='Order window')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publisher_packages', to='publisher.publisher', verbose_name='Publisher')),
                ('related_orders', models.ManyToManyField(related_name='publisher_related_orders', to='order.Order', verbose_name='Publisher related order')),
            ],
            options={
                'verbose_name': 'Publisher Package',
                'verbose_name_plural': 'Publisher packages',
                'unique_together': {('publisher', 'order_window')},
            },
        ),
        migrations.CreateModel(
            name='SchoolPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In transit'), ('issue', 'Issue'), ('delivered', 'Delivered')], default='pending', max_length=40, verbose_name='School package status')),
                ('total_price', models.IntegerField(default=0, verbose_name='Total price')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='Total quantity')),
                ('courier_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courier_package', to='package.courierpackage', verbose_name='Courier package')),
                ('order_window', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='order.orderwindow', verbose_name='Order window')),
                ('related_orders', models.ManyToManyField(related_name='school_related_orders', to='order.Order', verbose_name='School related order')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_packages', to=settings.AUTH_USER_MODEL, verbose_name='School')),
            ],
            options={
                'verbose_name': 'School Package',
                'verbose_name_plural': 'School packages',
                'unique_together': {('school', 'order_window')},
            },
        ),
        migrations.CreateModel(
            name='SchoolPackageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('snapshot', models.JSONField(blank=True, default=None, null=True, verbose_name='Snapshot')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('files', models.ManyToManyField(blank=True, to='common.ActivityLogFile', verbose_name='Flies')),
                ('school_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_package_logs', to='package.schoolpackage', verbose_name='School package')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolPackageBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_package_book', to='book.book', verbose_name='Book')),
                ('school_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_package', to='package.schoolpackage', verbose_name='School package')),
            ],
            options={
                'verbose_name': 'School package related book',
                'verbose_name_plural': 'School package related books',
            },
        ),
        migrations.CreateModel(
            name='PublisherPackageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('snapshot', models.JSONField(blank=True, default=None, null=True, verbose_name='Snapshot')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('files', models.ManyToManyField(blank=True, to='common.ActivityLogFile', verbose_name='Flies')),
                ('publisher_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_package_logs', to='package.publisherpackage', verbose_name='Publisher package')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublisherPackageBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publisher_package_book', to='book.book', verbose_name='Book')),
                ('publisher_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publisher_package', to='package.publisherpackage', verbose_name='Publisher package')),
            ],
            options={
                'verbose_name': 'Publisher package related book',
                'verbose_name_plural': 'Publisher related books',
            },
        ),
        migrations.CreateModel(
            name='CourierPackageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('snapshot', models.JSONField(blank=True, default=None, null=True, verbose_name='Snapshot')),
                ('courier_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_package_logs', to='package.courierpackage', verbose_name='Courier package')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('files', models.ManyToManyField(blank=True, to='common.ActivityLogFile', verbose_name='Flies')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
