# Generated by Django 3.2.12 on 2022-03-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courierpackage',
            name='related_orders',
        ),
    ]
