# Generated by Django 3.2.12 on 2022-02-23 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20220220_1232'),
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierpackage',
            name='order_window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='order.orderwindow', verbose_name='Order window'),
        ),
        migrations.AddField(
            model_name='publisherpackage',
            name='order_window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='order.orderwindow', verbose_name='Order window'),
        ),
        migrations.AddField(
            model_name='schoolpackage',
            name='order_window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='order.orderwindow', verbose_name='Order window'),
        ),
    ]
