# Generated by Django 3.2.12 on 2022-03-09 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20220302_1008'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierpackage',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Total price'),
        ),
        migrations.AddField(
            model_name='courierpackage',
            name='total_quantity',
            field=models.IntegerField(default=0, verbose_name='Total quantity'),
        ),
        migrations.AddField(
            model_name='publisherpackage',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Total price'),
        ),
        migrations.AddField(
            model_name='publisherpackage',
            name='total_quantity',
            field=models.IntegerField(default=0, verbose_name='Total quantity'),
        ),
        migrations.AddField(
            model_name='schoolpackage',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Total price'),
        ),
        migrations.AddField(
            model_name='schoolpackage',
            name='total_quantity',
            field=models.IntegerField(default=0, verbose_name='Total quantity'),
        ),
        migrations.CreateModel(
            name='SchoolPackageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('snapshot', models.JSONField(blank=True, default=None, null=True, verbose_name='Snapshot')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('files', models.ManyToManyField(blank=True, to='common.ActivityLogFile', verbose_name='Flies')),
                ('school_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_package_logs', to='package.schoolpackage', verbose_name='School package')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublisherPackageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('snapshot', models.JSONField(blank=True, default=None, null=True, verbose_name='Snapshot')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('files', models.ManyToManyField(blank=True, to='common.ActivityLogFile', verbose_name='Flies')),
                ('publisher_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_package_logs', to='package.publisherpackage', verbose_name='Publisher package')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourierPackageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('snapshot', models.JSONField(blank=True, default=None, null=True, verbose_name='Snapshot')),
                ('courier_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_package_logs', to='package.courierpackage', verbose_name='Courier package')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('files', models.ManyToManyField(blank=True, to='common.ActivityLogFile', verbose_name='Flies')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
