# Generated by Django 3.2.12 on 2022-03-11 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20220302_1008'),
        ('package', '0002_remove_courierpackage_related_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierpackage',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courier_package_municipality', to='common.municipality', verbose_name='Municipality'),
            preserve_default=False,
        ),
    ]
