# Generated by Django 3.2.12 on 2022-02-23 09:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0006_remove_publisher_email'),
        ('order', '0008_auto_20220220_1232'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('package', '0002_auto_20220223_1505'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publisherpackage',
            unique_together={('publisher', 'order_window')},
        ),
        migrations.AlterUniqueTogether(
            name='schoolpackage',
            unique_together={('school', 'order_window')},
        ),
    ]
