# Generated by Django 3.2.12 on 2022-03-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_courierpackage_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierpackage',
            name='is_eligible_for_incentive',
            field=models.BooleanField(default=False, verbose_name='Is eligible for incentive'),
        ),
        migrations.AddField(
            model_name='publisherpackage',
            name='incentive',
            field=models.IntegerField(default=0, verbose_name='Incentive'),
        ),
        migrations.AddField(
            model_name='schoolpackage',
            name='is_eligible_for_incentive',
            field=models.BooleanField(default=False, verbose_name='Is eligible for incentive'),
        ),
    ]
