# Generated by Django 3.2.12 on 2022-04-04 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_fix_book_categories'),
        ('order', '0004_migrate_existing_order_windows'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0004_auto_20220302_1008'),
        ('package', '0004_auto_20220323_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In transit'), ('issue', 'Issue'), ('delivered', 'Delivered')], default='pending', max_length=40, verbose_name='Institution package status')),
                ('total_price', models.IntegerField(default=0, verbose_name='Total price')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='Total quantity')),
                ('courier_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institution_courier_package', to='package.courierpackage', verbose_name='Courier package')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institution_packages', to=settings.AUTH_USER_MODEL, verbose_name='Institution')),
                ('order_window', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='order.orderwindow', verbose_name='Order window')),
                ('related_orders', models.ManyToManyField(related_name='institution_related_orders', to='order.Order', verbose_name='Institution related order')),
            ],
            options={
                'verbose_name': 'Institution package',
                'verbose_name_plural': 'Institution packages',
                'unique_together': {('institution', 'order_window')},
            },
        ),
        migrations.CreateModel(
            name='InstitutionPackageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('snapshot', models.JSONField(blank=True, default=None, null=True, verbose_name='Snapshot')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('files', models.ManyToManyField(blank=True, to='common.ActivityLogFile', verbose_name='Flies')),
                ('school_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_package_logs', to='package.institutionpackage', verbose_name='Institution package')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstitutionPackageBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institution_package_book', to='book.book', verbose_name='Book')),
                ('school_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institution_package', to='package.institutionpackage', verbose_name='Institution package')),
            ],
            options={
                'verbose_name': 'Institution package related book',
                'verbose_name_plural': 'Institution package related books',
            },
        ),
    ]
