# Generated by Django 3.2.12 on 2022-04-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_institutionpackage_institutionpackagebook_institutionpackagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierpackage',
            name='type',
            field=models.CharField(blank=True, choices=[('school', 'School'), ('institution', 'Institution')], max_length=40, verbose_name='Package type'),
        ),
    ]
