# Generated by Django 3.2.12 on 2022-04-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0007_rename_school_package_institutionpackagelog_institution_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherpackage',
            name='orders_export_file',
            field=models.FileField(blank=True, default=None, max_length=255, null=True, upload_to='publisher/exports/'),
        ),
    ]
