# Generated by Django 3.2.12 on 2022-02-21 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0004_baseactivitylogimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=20, null=True, verbose_name='transaction type')),
                ('payment_type', models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque')], max_length=20, null=True, verbose_name='payment type')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created at')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('cancelled', 'Cancelled')], default='pending', max_length=50, verbose_name='status')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payment',
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('system_comment', models.TextField(blank=True, null=True, verbose_name='system comment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('images', models.ManyToManyField(blank=True, to='common.BaseActivityLogImage', verbose_name='images')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.payment', verbose_name='payment')),
            ],
            options={
                'verbose_name': 'payment log',
                'verbose_name_plural': 'payment log',
            },
        ),
    ]
