# Generated by Django 3.2.12 on 2022-02-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=20, verbose_name='Transaction type')),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque')], max_length=20, verbose_name='Payment type')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created at')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('cancelled', 'Cancelled')], default='pending', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payment',
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('snapshot', models.JSONField(blank=True, default=None, null=True, verbose_name='Snapshot')),
            ],
            options={
                'verbose_name': 'Payment log',
                'verbose_name_plural': 'Payment log',
            },
        ),
    ]
