# Generated by Django 3.2.12 on 2022-02-23 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='payment_modified_by', to='user.user', verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_for',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.user', verbose_name='payment_paid_for'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_created_by', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque')], default=1, max_length=20, verbose_name='Payment type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default=1, max_length=20, verbose_name='Transaction type'),
            preserve_default=False,
        ),
    ]
