# Generated by Django 3.2.12 on 2022-03-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20220302_1008'),
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentlog',
            name='images',
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='files',
            field=models.ManyToManyField(blank=True, to='common.ActivityLogFile', verbose_name='Flies'),
        ),
    ]
