# Generated by Django 3.2.12 on 2022-02-23 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0003_auto_20220223_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paid_for',
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.user', verbose_name='payment_paid_by'),
            preserve_default=False,
        ),
    ]
